apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-mgmt-service-mysql
  labels:
    app: project-mgmt-service
spec:
  selector:
    matchLabels:
      app: project-mgmt-service
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: project-mgmt-service
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: bjjd
        - name: MYSQL_DATABASE
          value: project_db
        - name: MYSQL_USER
          value: project
        - name: MYSQL_PASSWORD
          value: project
        args:
          - "--ignore-db-dir=lost+found" #CHANGE
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: project-mgmt-service-mysql # DNS name
  labels:
    app: project-mgmt-service
spec:
  ports:
  - name: "mysql-port"
    port: 3306
    targetPort: 3306
  selector:
    app: project-mgmt-service
    tier: mysql
  clusterIP: None