apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1000Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: project-mgmt-service #Request of the storage for project-mgmt-service that can be fulfilled by PV.
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi #Request for the amount of storage
